// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sendora.Core.Database;

#nullable disable

namespace Sendora.Core.Migrations
{
    [DbContext(typeof(MailsContext))]
    [Migration("20250218104515_Layout")]
    partial class Layout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Sendora.Infrastructure.Models.MailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seen");

                    b.HasKey("Id");

                    b.ToTable("Mails");
                });
#pragma warning restore 612, 618
        }
    }
}
